[application]
name = "z"
enable = true

[application.workflows]
provider = "github_actions"
excluded_workflows = []

[[application.namespaces]]
type = "prod"

[application.namespaces.build]
build_workflow = "prod_workflow"

[application.namespaces.delivery]
target = "prod"
base_replica = 3
rollout_strategy = "rolling_upgrade"

[application.namespaces.appsignal]
enable = true
app_id = "5f5b5fcd7478204c00a6b127"
environment = "prod_gcp_searce"
default_namespace = "api"

[[application.namespaces]]
type = "staging"

[application.namespaces.build]
build_workflow = "staging_workflow"

[application.namespaces.delivery]
target = "staging"
base_replica = 3
rollout_strategy = "rolling_upgrade"

[application.namespaces.appsignal]
enable = true
app_id = "5f3d4ac40264447523321259"
environment = "staging_gcp_searce"
default_namespace = "api"

[application.addons]
