[application]
name = "my-first-application"
enable = true

[application.workflows]
provider = "github_actions"
excluded_workflows = ["Elixir CI"]
enable = true

[[application.namespaces]]
type = "prod"

[application.namespaces.build]
build_workflow = "prod-workflow"

[application.namespaces.delivery]
target = "prod"
base_replica = 3
rollout_strategy = "rolling_upgrade"

[application.addons.elixir_livebook]
enable = true
allowed_admins = []
