[package]
name = "wukong"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
dirs-next = "2.0.0"
indicatif = "0.16.2"
lazy_static = "1.4.0"
serde = { version = "1.0.137", features = ["derive"] }
toml = "0.5"
tabled = "0.7.0"
dialoguer = "0.10.1"
anyhow = "1.0.57"
