[package]
name = "wukong"
version = "0.0.3-alpha2"
edition = "2021"

[profile.release]
strip = true
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive", "wrap_help"] }
clap_complete = { version = "4" }
dirs = "4.0"
indicatif = "0.17.0"
lazy_static = "1.4.0"
tabled = { version = "0.9.0", features = ["color"] }
dialoguer = "0.10.1"

# Making https request
reqwest = "0.11.11"
graphql_client = { version = "0.11.0", features = ["reqwest"] }
# Async runtime
tokio = { version = "1.19.2", features = ["full"] }

# Error handling
anyhow = "1.0.57"

# Serialization and Deserialization
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"
thiserror = "1.0.31"
log = "0.4.17"
chrono = "0.4.19"

# Auth
openidconnect = "2.3.2"
url = "2.2.2"
webbrowser = "0.7.1"
env_config = { package = "config", version = "0.13.2"}

openssl = { version = "*", features = ["vendored"] }
owo-colors = "3.5.0"
chrono-humanize = "0.2.2"
base64 = "0.13.0"
console = "0.15.2"

[dev-dependencies]
httpmock = "0.6.6"
