[package]
name = "wukong"
version = "0.0.4-beta1"
edition = "2021"

[features]
prod = []

[profile.release]
strip = true
lto = true

[[bench]]
name = "output_tokenizer_benchmark"
harness = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive", "wrap_help", "cargo"] }
clap_complete = { version = "4" }
dirs = "4.0"
indicatif = "0.17.0"
tabled = { version = "0.10.0", features = ["color"] }
dialoguer = "0.10.1"

# Making https request
reqwest = "0.11.11"
graphql_client = { version = "0.12.0", features = ["reqwest-rustls"] }
# Async runtime
tokio = { version = "1.24.2", features = ["full"] }

# Error handling
anyhow = "1.0.57"

# Serialization and Deserialization
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0"
toml = "0.7"
thiserror = "1.0.31"
chrono = { version = "0.4.23", default-features = false, features = ["std"] }
time-humanize = "0.1.3"

# logger
log = "0.4.17"
clap-verbosity-flag = "2.0.0"

# Auth
openidconnect = "2.3.2"
url = "2.2.2"
webbrowser = "0.8"

openssl = { version = "*", features = ["vendored"] }
owo-colors = "3.5.0"
base64 = "0.21.0"
human-panic = "1.0.3"
once_cell = "1.16.0"
ctrlc = { version = "3.2.3", features = ["termination"] }
edit = "0.1.4"

# Telemetry
wukong_telemetry_macro = { path = "crates/wukong_telemetry_macro" }
regex = "1.7.0"

[dev-dependencies]
httpmock = "0.6.6"
criterion = "0.4"
rexpect = "0.5.0"
assert_fs = "1.0.10"
aion = "0.2.0"
insta = { version = "1.26.0", features = ["yaml"] }
assert_cmd = "2.0.8"

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3