[package]
name = "wukong"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.5", features = ["derive"] }
dirs-next = "2.0.0"
indicatif = "0.16.2"
lazy_static = "1.4.0"
tabled = "0.7.0"
dialoguer = "0.10.1"

# Making https request
reqwest = "0.11.11"
graphql_client = { version = "0.10.0", features = ["reqwest"] }
# Async runtime
tokio = { version = "1.19.2", features = ["full"] }

# Error handling
anyhow = "1.0.57"

# Serialization and Deserialization
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"
thiserror = "1.0.31"
log = "0.4.17"
ansi_term = "0.12.1"
chrono = "0.4.19"
