[profile.release]
strip = true
lto = true

[profile.dev]
opt-level = 0
debug = true
split-debuginfo = "packed"

[profile.dev.package.insta]
opt-level = 3

[workspace]
members = ["cli", "sdk", "telemetry", "telemetry-macro"]
