[package]
name = "wukong"
version = "1.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wukong-sdk = { path = "../sdk/" }

clap = { version = "4.3.8", features = ["derive", "wrap_help", "cargo"] }
clap_complete = "4.3.1"
dialoguer = "0.10.4"
indicatif = { version = "0.17.5", features = ["rayon"] }
tabled = { version = "0.10.0", features = ["color"] }
tokio = { version = "1.28.2", features = ["full"] }
owo-colors = "3.5.0"
serde = { version = "1.0.164", features = ["serde_derive"] }
once_cell = "1.18.0"

# logging
log = "0.4.19"
clap-verbosity-flag = "2.0.0"
thiserror = "1.0.40"
dirs = "5.0.1"
toml = "0.7.5"
aion = "0.2.0"
openidconnect = "3.2.0"
chrono = { version = "0.4.26", default-features = false, features = ["std"] }

human-panic = "1.1.5"
time-humanize = "0.1.3"
chrono-tz = "0.8.1"
regex = "1.7.0"
edit = "0.1.4"
base64 = "0.21.0"
reqwest = "0.11.11"
yup-oauth2 = "8.3.0"
webbrowser = "0.8"
prost = "0.11.9"
tonic = { version = "0.9.2", features = ["tls", "tls-webpki-roots"] }
prost-types = "0.11.8"
