import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :wukong_api_proxy, WukongApiProxyWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "f08E8/lkFpFQzpe6xLWhIdzOhZcFp0MSyfyfTxWLx+RssO2fqrvSSeXPbOqzzutM",
  watchers: []

database =
  System.get_env("POSTGRES_DATABASE") || "wukong_api_test#{System.get_env("MIX_TEST_PARTITION")}"

database_hostname = System.get_env("POSTGRES_HOSTNAME") || "localhost"
database_port = System.get_env("POSTGRES_PORT") || 5432
database_username = System.get_env("POSTGRES_USERNAME") || "postgres"
database_password = System.get_env("POSTGRES_PASSWORD") || "postgres"

config :wukong_api_proxy, WukongApiProxy.Repo,
  username: database_username,
  password: database_password,
  hostname: database_hostname,
  port: database_port,
  database: database,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Import development secrets
# wukong.mindvalley.dev/config-secrets-location: vault:secret/wukong-cli/sandboxes#dev.secrets.exs
import_config("dev.secrets.exs")
