name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: CI
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest ]
        rust: [ stable ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
          components: rustfmt, clippy
      - uses: actions/checkout@v3

      # - uses: actions-rs/toolchain@v1
      #   with:
      #     profile: minimal
      #     toolchain: stable
      #     override: true
      #     components: rustfmt, clippy

      - name: Build Wukong CLI
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --release

      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Check clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Test Wukong CLI
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
